name: CI/CD pipeline

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secret for Docker username
                password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secret for Docker password
      

            - name: Build Docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

            - name: Push Docker image to Docker Hub
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}            
        

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: prod
        steps:
            - name: checkout code for deploy
              uses: actions/checkout@v4


            - name: Deploying into kubernetes cluster
              run: |
                echo "deploying"