name: CI/CD pipeline

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            
            - name: checkout code
              uses: actions/checkout@v4

            - name: building the job
              run: |
                echo "building"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout code for deploy
              uses: actions/checkout@v4


            - name: Deploying into kubernetes cluster
              run: |
                echo "deploying"